version: '3.5'

services:

  prometheus:
    image: jahrik/arm-alertmanager:aarch64
    ports:
      - 9093:9093
    volumes:
      - /mnt/g1/alertmanager:/alertmanager
    networks:
      - monitor
    deploy:
      placement:
        constraints:
          - node.labels.arch == aarch64

networks:
  monitor:
    name: monitor
    driver: overlay
    external: true
