---
services:
  alertmanager:
    image: jahrik/arm-alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - /mnt/g1/alertmanager:/alertmanager
    networks:
      - monitor

networks:
  monitor:
    name: monitor
    driver: overlay
    external: true
