FROM arm64v8/golang

RUN git clone https://github.com/prometheus/alertmanager.git
RUN cd alertmanager && \
  make build && \
  cp alertmanager /bin/alertmanager

RUN mkdir /etc/alertmanager
COPY config.yml /etc/alertmanager/config.yml

RUN mkdir /alertmanager
VOLUME [ "/alertmanager" ]

EXPOSE 9093
ENTRYPOINT [ "/bin/alertmanager" ]
CMD [ "--config.file=/etc/alertmanager/config.yml", "--storage.path=/alertmanager" ]
